export const dogProducts = [
  { name: 'Green Nassfutter Vegan',
    brand: 'Pets Deli',
    img: 'greenVegan.jpg',
    img2: 'greenVegan2.jpg',
    price: '19,99',
    quantity: '6 x 400g',
    type: 'Nassfutter',
    ingredients: ['Lupinen', 'Mangold', 'Süßkartoffel', 'Zucchini'],
    count: '1',
    lifestage: 'Adults',
  }, { name: 'Green Nassfutter Veggie',
    brand: 'Pets Deli',
    img: 'greenVeggie.jpg',
    img2: 'greenVeggie2.jpg',
    price: '19,99',
    quantity: '6 x 400g',
    type: 'Nassfutter',
    ingredients: ['Hüttenkäse', 'Zucchini', 'Quinoa', 'Spinat'],
    count: '1',
    lifestage: 'Adult',
  }, { name: 'Clean Protein Dog Food',
    brand: 'Wild Earth',
    img: 'protein.jpg',
    img2: 'protein2.jpg',
    price: '29',
    quantity: '2kg',
    type: 'dry',
    ingredients: ['chickpeas', 'oats', 'pumpkin', 'Spinach'],
    count: '1',
    lifestage: 'Adult',
  }, { name: 'Green Trockenfutter Extra Protein',
    brand: 'Pets Deli',
    img: 'greenDry.jpg',
    img2: 'greenDry2.jpg',
    price: '39,99',
    quantity: '4 kg',
    type: 'dry',
    ingredients: ['Insects', 'Amaranth', 'Pastinake', 'Cranberry'],
    count: '1',
    lifestage: 'Adult',
  }, { name: 'Green Trockenfutter Classic',
    brand: 'Pets Deli',
    img: 'greenDryC.jpg',
    img2: 'greenDryC2.jpg',
    price: '34,99',
    quantity: '4 kg',
    type: 'dry',
    ingredients: [ 'Insekten', 'Kartoffel', 'Erbsen', 'Apfel' ],
    count: '1',
    lifestage: 'every',
  }, { name: 'Superfood Dog Treats With Koji',
    brand: 'Pets Deli',
    img: 'peanut-butter-dog-treats.jpg',
    img2: 'koji-dog-treats.jpg',
    price: '10,00',
    quantity: '140g',
    type: 'Treat',
    ingredients: ['Oats', 'Penutbutter', 'Pumpkin', 'Chicory'],
    count: '1',
    lifestage: 'all stages',
  },
];
