export const dogProducts = [
  { name: 'Green Nassfutter Vegan',
    brand: 'Pets Deli',
    img: '',
    img2: '',
    price: '19,99',
    taxes: '8,33',
    quantity: '6 x 400g',
    type: 'Nassfutter',
    ingredients: ['Lupinen', 'Mangold', 'Süßkartoffel', 'Zucchini'],
    count: '1',
    lifestage: 'Adults',
  }, { name: '',
    brand: 'Pets Deli',
    img: '',
    img2: '',
    price: '',
    quantity: '',
    type: '',
    ingredients: [],
    count: '1',
    lifestage: '',
  }, { name: '',
    brand: 'Pets Deli',
    img: '',
    img2: '',
    price: '',
    quantity: '',
    type: '',
    ingredients: [],
    count: '1',
    lifestage: '',
  }, { name: '',
    brand: 'Pets Deli',
    img: '',
    img2: '',
    price: '',
    quantity: '',
    type: '',
    ingredients: [],
    count: '1',
    lifestage: '',
  }, { name: '',
    brand: 'Pets Deli',
    img: '',
    img2: '',
    price: '',
    quantity: '',
    type: '',
    ingredients: [],
    count: '1',
    lifestage: '',
  }, { name: '',
    brand: 'Pets Deli',
    img: '',
    img2: '',
    price: '',
    quantity: '',
    type: '',
    ingredients: [],
    count: '1',
    lifestage: '',
  },
];
